/* Generated By:JavaCC: Do not edit this line. NFFParserConstants.java */
package org.cybergarage.x3d.parser.sense8;

public interface NFFParserConstants {

  int EOF = 0;
  int COMMENT = 4;
  int INDEX = 18;
  int NUMBER = 19;
  int NAME = 20;
  int VALUE = 21;
  int EXPONENT = 22;
  int COLOR = 23;
  int TEXTURE = 24;
  int PORTAL = 25;
  int POLYID = 26;
  int EOL = 27;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<COMMENT>",
    "\"nff\"",
    "\"version\"",
    "\"viewpos\"",
    "\"viewdir\"",
    "\"mtable\"",
    "\"N\"",
    "\"norm\"",
    "\"rgb\"",
    "\"uv\"",
    "\"both\"",
    "\"rot\"",
    "\"scale\"",
    "\"trans\"",
    "<INDEX>",
    "<NUMBER>",
    "<NAME>",
    "<VALUE>",
    "<EXPONENT>",
    "<COLOR>",
    "<TEXTURE>",
    "<PORTAL>",
    "<POLYID>",
    "\"\\n\"",
  };

}
