/* Generated By:JavaCC: Do not edit this line. STLAsciiParserConstants.java */
package org.cybergarage.x3d.parser.threedsystems;

public interface STLAsciiParserConstants {

  int EOF = 0;
  int NUMBER = 15;
  int NAME = 16;
  int FLOAT_NUMBER = 17;
  int EXPONENT = 18;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"solid\"",
    "\"endsolid\"",
    "\"facet\"",
    "\"endfacet\"",
    "\"outer\"",
    "\"loop\"",
    "\"endloop\"",
    "\"color\"",
    "\"vertex\"",
    "\"normal\"",
    "<NUMBER>",
    "<NAME>",
    "<FLOAT_NUMBER>",
    "<EXPONENT>",
  };

}
