/* Generated By:JavaCC: Do not edit this line. OBJParserConstants.java */
package org.cybergarage.x3d.parser.wavefront;

public interface OBJParserConstants {

  int EOF = 0;
  int COMMENT = 5;
  int ID = 18;
  int NAME = 19;
  int FLOAT_NUMBER = 20;
  int EXPONENT = 21;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<COMMENT>",
    "\"v\"",
    "\"vn\"",
    "\"g\"",
    "\"s\"",
    "\"mg\"",
    "\"o\"",
    "\"/\"",
    "\"f\"",
    "\"usemap\"",
    "\"maplib\"",
    "\"usemtl\"",
    "\"mtlib\"",
    "<ID>",
    "<NAME>",
    "<FLOAT_NUMBER>",
    "<EXPONENT>",
  };

}
